kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-pv-role
rules:
- apiGroups: [""]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch", "create", "update"]